module.exports = {
  async up(queryInterface) {
    await queryInterface.bulkInsert('Images', [{
      advertisementId: 1,
      image: '/img/1.png',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      advertisementId: 1,
      image: '/img/2.png',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      advertisementId: 1,
      image: '/img/3.png',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      advertisementId: 2,
      image: '/img/4.png',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      advertisementId: 2,
      image: '/img/5.png',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      advertisementId: 2,
      image: '/img/6.png',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      advertisementId: 3,
      image: '/img/7.png',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      advertisementId: 3,
      image: '/img/8.png',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      advertisementId: 3,
      image: '/img/9.png',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      advertisementId: 4,
      image: '/img/10.png',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      advertisementId: 4,
      image: '/img/11.png',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      advertisementId: 4,
      image: '/img/12.png',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      advertisementId: 5,
      image: '/img/13.png',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      advertisementId: 5,
      image: '/img/14.png',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      advertisementId: 6,
      image: '/img/15.png',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      advertisementId: 6,
      image: '/img/16.png',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      advertisementId: 6,
      image: '/img/17.png',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      advertisementId: 7,
      image: '/img/18.png',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      advertisementId: 7,
      image: '/img/19.png',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      advertisementId: 8,
      image: '/img/20.png',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      advertisementId: 8,
      image: '/img/21.png',
      createdAt: new Date(),
      updatedAt: new Date(),
    },

    {
      advertisementId: 9,
      image: '/img/22.png',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      advertisementId: 9,
      image: '/img/23.png',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      advertisementId: 9,
      image: '/img/24.png',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      advertisementId: 10,
      image: '/img/25.png',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      advertisementId: 10,
      image: '/img/26.png',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      advertisementId: 11,
      image: '/img/27.png',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      advertisementId: 11,
      image: '/img/28.png',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      advertisementId: 11,
      image: '/img/29.png',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      advertisementId: 12,
      image: '/img/30.png',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      advertisementId: 12,
      image: '/img/31.png',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      advertisementId: 13,
      image: '/img/32.png',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      advertisementId: 13,
      image: '/img/33.png',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      advertisementId: 14,
      image: '/img/34.png',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      advertisementId: 15,
      image: '/img/35.png',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      advertisementId: 15,
      image: '/img/36.png',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      advertisementId: 16,
      image: '/img/37.png',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      advertisementId: 16,
      image: '/img/38.png',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      advertisementId: 16,
      image: '/img/39.png',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      advertisementId: 17,
      image: '/img/40.png',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      advertisementId: 17,
      image: '/img/41.png',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      advertisementId: 17,
      image: '/img/42.png',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      advertisementId: 18,
      image: '/img/43.png',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      advertisementId: 18,
      image: '/img/44.png',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      advertisementId: 18,
      image: '/img/45.png',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      advertisementId: 19,
      image: '/img/46.png',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      advertisementId: 20,
      image: '/img/47.png',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      advertisementId: 20,
      image: '/img/48.png',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      advertisementId: 20,
      image: '/img/49.png',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      advertisementId: 21,
      image: '/img/50.png',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      advertisementId: 21,
      image: '/img/51.png',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      advertisementId: 21,
      image: '/img/52.png',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      advertisementId: 22,
      image: '/img/53.png',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      advertisementId: 22,
      image: '/img/54.png',
      createdAt: new Date(),
      updatedAt: new Date(),
    },

    ], {});
  },

  async down(queryInterface) {
  },
};
